version: '2'
services:
  pg:
    image: postgres:9.4
    expose:
      - "5432"
  redis:
    image: redis
    expose:
      - "6379"

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bundle exec sidekiq -C config/sidekiq.yml
    env_file: '.env.development'
    links:
      - pg
      - redis

  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command:  bash -c "rm -f ./tmp/pids/server.pid && bin/rails server --port 3000 --binding 0.0.0.0"
    env_file: '.env.development'
    ports:
      - "3000:3000"
    volumes:
      - .:/notification_service_ruby
    links:
      - pg
      - redis